/* This file was generated by syncqt. */
#ifndef QT_QTQUICK_VERSION_H
#define QT_QTQUICK_VERSION_H

#define QTQUICK_VERSION_STR "6.7.2"

#define QTQUICK_VERSION 0x060702

#endif // QT_QTQUICK_VERSION_H
