// Copyright (C) 2021 The Qt Company Ltd.
// SPDX-License-Identifier: LicenseRef-Qt-Commercial OR LGPL-3.0-only OR GPL-2.0-only OR GPL-3.0-only

#ifndef QTLABSFOLDERLISTMODELEXPORTS_P_H
#define QTLABSFOLDERLISTMODELEXPORTS_P_H

// This file is autogenerated. Changes will be overwritten.

//
//  W A R N I N G
//  -------------
//
// This file is not part of the Qt API.  It exists purely as an
// implementation detail.  This header file may change from version to
// version without notice, or even be removed.
//
// We mean it.
//

#include <QtLabsFolderListModel/qtlabsfolderlistmodelexports.h>

#define Q_LABSFOLDERLISTMODEL_PRIVATE_EXPORT Q_LABSFOLDERLISTMODEL_EXPORT

#endif // QTLABSFOLDERLISTMODELEXPORTS_P_H
