QT.svgwidgets_private.VERSION = 6.7.2
QT.svgwidgets_private.name = QtSvgWidgets
QT.svgwidgets_private.module =
QT.svgwidgets_private.libs = $$QT_MODULE_LIB_BASE
QT.svgwidgets_private.includes = $$QT_MODULE_INCLUDE_BASE/QtSvgWidgets/6.7.2 $$QT_MODULE_INCLUDE_BASE/QtSvgWidgets/6.7.2/QtSvgWidgets
QT.svgwidgets_private.frameworks = 
QT.svgwidgets_private.depends = core_private gui_private widgets_private svgwidgets
QT.svgwidgets_private.uses = 
QT.svgwidgets_private.module_config = v2 internal_module
QT.svgwidgets_private.enabled_features = 
QT.svgwidgets_private.disabled_features = 
