QT.openglwidgets_private.VERSION = 6.7.2
QT.openglwidgets_private.name = QtOpenGLWidgets
QT.openglwidgets_private.module =
QT.openglwidgets_private.libs = $$QT_MODULE_LIB_BASE
QT.openglwidgets_private.includes = $$QT_MODULE_INCLUDE_BASE/QtOpenGLWidgets/6.7.2 $$QT_MODULE_INCLUDE_BASE/QtOpenGLWidgets/6.7.2/QtOpenGLWidgets
QT.openglwidgets_private.frameworks = 
QT.openglwidgets_private.depends = openglwidgets
QT.openglwidgets_private.uses = 
QT.openglwidgets_private.module_config = v2 internal_module
QT.openglwidgets_private.enabled_features = 
QT.openglwidgets_private.disabled_features = 
