QT.gui_private.VERSION = 6.7.2
QT.gui_private.name = QtGui
QT.gui_private.module =
QT.gui_private.libs = $$QT_MODULE_LIB_BASE
QT.gui_private.includes = $$QT_MODULE_INCLUDE_BASE/QtGui/6.7.2 $$QT_MODULE_INCLUDE_BASE/QtGui/6.7.2/QtGui
QT.gui_private.frameworks = 
QT.gui_private.depends = core_private gui
QT.gui_private.uses = 
QT.gui_private.module_config = v2 internal_module
QT.gui_private.enabled_features = directwrite directwrite3 direct2d direct2d1_1 freetype harfbuzz vkgen gif ico jpeg png imageio-text-loading tuiotouch multiprocess raster-64bit raster-fp
QT.gui_private.disabled_features = accessibility-atspi-bridge directfb evdev system-freetype fontconfig system-harfbuzz qqnx_imf integrityfb kms drm_atomic libinput integrityhid libinput-axis-api libinput-hires-wheel-support linuxfb vsp2 vnc mtdev vkkhrdisplay egl_x11 eglfs eglfs_brcm eglfs_egldevice eglfs_gbm eglfs_vsp2 eglfs_mali eglfs_viv eglfs_rcar eglfs_viv_wl eglfs_openwfd eglfs_x11 system-jpeg system-png tslib xcb-glx xcb-egl-plugin xcb-native-painting xrender xcb-xlib xcb-sm system-xcb-xinput xkbcommon xkbcommon-x11 xlib graphicsframecapture
QMAKE_LIBS_OPENGL = 
QMAKE_LIBS_VULKAN = 
