QT.core_private.VERSION = 6.7.2
QT.core_private.name = QtCore
QT.core_private.module =
QT.core_private.libs = $$QT_MODULE_LIB_BASE
QT.core_private.includes = $$QT_MODULE_INCLUDE_BASE/QtCore/6.7.2 $$QT_MODULE_INCLUDE_BASE/QtCore/6.7.2/QtCore
QT.core_private.frameworks = 
QT.core_private.depends = core
QT.core_private.uses = 
QT.core_private.module_config = v2 internal_module
QT.core_private.enabled_features = doubleconversion mimetype-database posix_sem sha3-fast hijricalendar datetimeparser pcre2 reduce_exports x86intrin sse2 sse3 ssse3 sse4_1 sse4_2 avx f16c avx2 avx512f avx512er avx512cd avx512pf avx512dq avx512bw avx512vl avx512ifma avx512vbmi avx512vbmi2 aesni vaes rdrnd rdseed shani alloca_malloc_h alloca dbus gui network printsupport sql testlib widgets xml openssl relocatable force_debug_info largefile precompile_header sse2 sse3 ssse3 sse4_1 sse4_2 avx f16c avx2 avx512f avx512er avx512cd avx512pf avx512dq avx512bw avx512vl avx512ifma avx512vbmi avx512vbmi2 aesni vaes rdrnd rdseed shani
QT.core_private.disabled_features = clock-gettime close_range system-doubleconversion dladdr futimens getauxval getentropy glib icu inotify journald system-libb2 linkat system-pcre2 poll_ppoll poll_pollts poll_poll poll_select posix_shm qqnx_pps renameat2 slog2 syslog sysv_sem sysv_shm backtrace cpp-winrt lttng etw ctf forkfd_pidfd poll-exit-on-error openssl-hash use_bfd_linker use_gold_linker use_lld_linker use_mold_linker android-style-assets gc_binaries developer-build private_tests debug elf_private_full_version no_direct_extern_access mips_dsp mips_dspr2 neon arm_crc32 arm_crypto posix_fallocate alloca_h stack-protector-strong system-zlib stdlib-libcpp dbus-linked libudev dlopen intelcet
QMAKE_INCDIR_OPENSSL = C:/openssl/include
QMAKE_LIBS_OPENSSL = C:/openssl/lib/libssl.lib
QMAKE_LIBS_LIBATOMIC = 
QMAKE_LIBS_LIBRT = 
