QT.network_private.VERSION = 6.7.2
QT.network_private.name = QtNetwork
QT.network_private.module =
QT.network_private.libs = $$QT_MODULE_LIB_BASE
QT.network_private.includes = $$QT_MODULE_INCLUDE_BASE/QtNetwork/6.7.2 $$QT_MODULE_INCLUDE_BASE/QtNetwork/6.7.2/QtNetwork
QT.network_private.frameworks = 
QT.network_private.depends = core_private network
QT.network_private.uses = 
QT.network_private.module_config = v2 internal_module
QT.network_private.enabled_features = system-proxies networklistmanager publicsuffix-qt
QT.network_private.disabled_features = libresolv libproxy linux-netlink res_setservers publicsuffix-system
