QT.labswavefrontmesh_private.VERSION = 6.7.2
QT.labswavefrontmesh_private.name = QtLabsWavefrontMesh
QT.labswavefrontmesh_private.module =
QT.labswavefrontmesh_private.libs = $$QT_MODULE_LIB_BASE
QT.labswavefrontmesh_private.includes = $$QT_MODULE_INCLUDE_BASE/QtLabsWavefrontMesh/6.7.2 $$QT_MODULE_INCLUDE_BASE/QtLabsWavefrontMesh/6.7.2/QtLabsWavefrontMesh
QT.labswavefrontmesh_private.frameworks = 
QT.labswavefrontmesh_private.depends = labswavefrontmesh
QT.labswavefrontmesh_private.uses = 
QT.labswavefrontmesh_private.module_config = v2 internal_module
QT.labswavefrontmesh_private.enabled_features = 
QT.labswavefrontmesh_private.disabled_features = 
