QT.qmlintegration_private.VERSION = 6.7.2
QT.qmlintegration_private.name = QtQmlIntegration
QT.qmlintegration_private.module =
QT.qmlintegration_private.libs = $$QT_MODULE_LIB_BASE
QT.qmlintegration_private.includes = $$QT_MODULE_INCLUDE_BASE/QtQmlIntegration/6.7.2 $$QT_MODULE_INCLUDE_BASE/QtQmlIntegration/6.7.2/QtQmlIntegration
QT.qmlintegration_private.frameworks = 
QT.qmlintegration_private.depends = 
QT.qmlintegration_private.uses = 
QT.qmlintegration_private.module_config = v2 internal_module
QT.qmlintegration_private.enabled_features = 
QT.qmlintegration_private.disabled_features = 
