QT.quickdialogs2utils_private.VERSION = 6.7.2
QT.quickdialogs2utils_private.name = QtQuickDialogs2Utils
QT.quickdialogs2utils_private.module =
QT.quickdialogs2utils_private.libs = $$QT_MODULE_LIB_BASE
QT.quickdialogs2utils_private.includes = $$QT_MODULE_INCLUDE_BASE/QtQuickDialogs2Utils/6.7.2 $$QT_MODULE_INCLUDE_BASE/QtQuickDialogs2Utils/6.7.2/QtQuickDialogs2Utils
QT.quickdialogs2utils_private.frameworks = 
QT.quickdialogs2utils_private.depends = quickdialogs2utils
QT.quickdialogs2utils_private.uses = 
QT.quickdialogs2utils_private.module_config = v2 internal_module
QT.quickdialogs2utils_private.enabled_features = 
QT.quickdialogs2utils_private.disabled_features = 
