QT.statemachineqml_private.VERSION = 6.7.2
QT.statemachineqml_private.name = QtStateMachineQml
QT.statemachineqml_private.module =
QT.statemachineqml_private.libs = $$QT_MODULE_LIB_BASE
QT.statemachineqml_private.includes = $$QT_MODULE_INCLUDE_BASE/QtStateMachineQml/6.7.2 $$QT_MODULE_INCLUDE_BASE/QtStateMachineQml/6.7.2/QtStateMachineQml
QT.statemachineqml_private.frameworks = 
QT.statemachineqml_private.depends = statemachineqml
QT.statemachineqml_private.uses = 
QT.statemachineqml_private.module_config = v2 internal_module
QT.statemachineqml_private.enabled_features = 
QT.statemachineqml_private.disabled_features = 
