QT.scxmlqml_private.VERSION = 6.7.2
QT.scxmlqml_private.name = QtScxmlQml
QT.scxmlqml_private.module =
QT.scxmlqml_private.libs = $$QT_MODULE_LIB_BASE
QT.scxmlqml_private.includes = $$QT_MODULE_INCLUDE_BASE/QtScxmlQml/6.7.2 $$QT_MODULE_INCLUDE_BASE/QtScxmlQml/6.7.2/QtScxmlQml
QT.scxmlqml_private.frameworks = 
QT.scxmlqml_private.depends = scxmlqml
QT.scxmlqml_private.uses = 
QT.scxmlqml_private.module_config = v2 internal_module
QT.scxmlqml_private.enabled_features = 
QT.scxmlqml_private.disabled_features = 
