/* This file was generated by syncqt. */
#ifndef QT_QTQMLDEBUG_VERSION_H
#define QT_QTQMLDEBUG_VERSION_H

#define QTQMLDEBUG_VERSION_STR "6.7.2"

#define QTQMLDEBUG_VERSION 0x060702

#endif // QT_QTQMLDEBUG_VERSION_H
