// Copyright (C) 2021 The Qt Company Ltd.
// SPDX-License-Identifier: LicenseRef-Qt-Commercial OR LGPL-3.0-only OR GPL-2.0-only OR GPL-3.0-only

#ifndef QTQUICKCONTROLS2IMPLEXPORTS_P_H
#define QTQUICKCONTROLS2IMPLEXPORTS_P_H

// This file is autogenerated. Changes will be overwritten.

//
//  W A R N I N G
//  -------------
//
// This file is not part of the Qt API.  It exists purely as an
// implementation detail.  This header file may change from version to
// version without notice, or even be removed.
//
// We mean it.
//

#include <QtQuickControls2Impl/qtquickcontrols2implexports.h>

#define Q_QUICKCONTROLS2IMPL_PRIVATE_EXPORT Q_QUICKCONTROLS2IMPL_EXPORT

#endif // QTQUICKCONTROLS2IMPLEXPORTS_P_H
