name: CMake

on:
  push:
    branches: '**'
  pull_request:
    branches: [ "main" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v3

      - name: Install Qt on Windows
        if: matrix.os == 'windows-latest'
        uses: jurplel/install-qt-action@v4
        with:
          version: '6.7.2'
          host: 'windows'
          target: 'desktop'
          arch: 'win64_msvc2019_64'
          modules: 'qtscxml'

      - name: Install Qt on macOS
        if: matrix.os == 'macos-latest'
        uses: jurplel/install-qt-action@v4
        with:
          version: '6.7.2'
          host: 'mac'
          target: 'desktop'
          arch: 'clang_64'
          modules: 'qtscxml'

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

      - name: Test
        working-directory: ${{github.workspace}}/build
        run: ctest -C ${{env.BUILD_TYPE}}

      - name: Upload .app Bundle
        if: matrix.os == 'macos-latest'
        uses: actions/upload-artifact@v3
        with:
          name: Minesweeper.app
          path: ${{github.workspace}}/build/macos_bin/Minesweeper.app

      - name: Package Windows Installer with CPack
        if: matrix.os == 'windows-latest'
        run: |
          cd ${{github.workspace}}/build
          cpack -G NSIS

      - name: Upload Windows Installer
        if: matrix.os == 'windows-latest'
        uses: actions/upload-artifact@v3
        with:
          name: Minesweeper-win64-installer.exe
          path: ${{github.workspace}}/build/Minesweeper-*-win64.exe