name: CMake Build

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        build_type: [Release]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies on Windows
        if: runner.os == 'Windows'
        run: |
          choco install qt --version=6.7.2 --pre --no-progress
          choco install nsis --no-progress

      - name: Install dependencies on macOS
        if: runner.os == 'macOS'
        run: |
          brew update
          brew install qt@6.7.2

      - name: Configure CMake
        run: |
          mkdir -p build
          cd build
          cmake .. -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}

      - name: Build
        run: |
          cd build
          cmake --build . --config ${{ matrix.build_type }}

      - name: Test
        run: |
          cd build
          ctest --output-on-failure